package ru.itmo.nemat.orchestrator.model;

public enum WorkflowStatus {
    RECEIVED,
    AWAITING_CURATOR_ACTION,
    RESERVATION_PENDING,
    RESERVATION_BLOCKED,
    AI_PROCESSING,
    AI_FAILED,
    AWAITING_APPROVAL,
    REJECTED,
    APPROVED,
    BILLING_PENDING,
    BILLING_FAILED,
    SENDING_TO_STUDENT,
    SENT_TO_STUDENT,
    COMPLETED,
    REFUND_PENDING,
    DELIVERY_FAILED_REFUNDED,
    REFUND_FAILED,
    DELIVERY_FAILED,
    CANCELLED
}
